Repository kennyphan100/SOEN341, pull requests merged in 2022-02, with the labels that each got.

#44 #43 Update home page UI
  public/css/styles.css
  public/images/4watches.webp
  public/images/bulova_watch.jpg
  public/images/google_home.jpg
  public/images/slide_watch.jpg
  public/images/twilight.jpg
  public/images/watches.jpg
  resources/views/home/index.blade.php
  resources/views/layouts/base.blade.php
Labels: task

#50 #45 Fix CSS bug on deployed website
  resources/views/layouts/base.blade.php
Labels: bug

#51 #46 Create contact page UI
  app/Http/Controllers/ContactFormController.php
  app/Mail/ContactFormMail.php
  public/css/styles.css
  resources/views/contact/create.blade.php
  resources/views/emails/contact/contact-form.blade.php
  resources/views/layouts/base.blade.php
  routes/web.php
Labels: task

#56 #52 Redirect successful login to home page
  resources/views/home/index.blade.php
  resources/views/layouts/base.blade.php
  routes/web.php
Labels: bug

#66 #64 Fix CSS on products page
  public/css/products.css
  resources/views/products/index.blade.php
Labels: bug

#70 #40 Create product page UI
  app/Http/Controllers/ProductsController.php
  public/css/product.css
  public/css/products.css
  resources/views/products/index.blade.php
  resources/views/products/show.blade.php
  routes/web.php
Labels: task

#73 #22 Implement shopping cart functionality
  app/Http/Controllers/CartController.php
  app/Http/Controllers/CategoriesController.php
  app/Http/Controllers/ProductsController.php
  composer.json
  composer.lock
  config/cart.php
  public/css/cart/cart.css
  public/images/pepe_crying.png
  resources/views/cart/cart.blade.php
  resources/views/cart/index.blade.php
  resources/views/categories/show.blade.php
  resources/views/layouts/base.blade.php
  resources/views/products/show.blade.php
  routes/web.php
Labels: task

#83 #80 Fix shopping cart bug
  app/Http/Controllers/CartController.php
  resources/views/cart/index.blade.php
Labels: bug

#85 #36 Created the checkout functionality
  app/Http/Controllers/OrderController.php
  app/Models/Order.php
  database/migrations/2022_02_15_015851_create_orders_table.php
  resources/views/cart/index.blade.php
  resources/views/order/index.blade.php
  resources/views/order/orderMade.blade.php
  routes/web.php
Labels: task

#94 #82 Fix CSS on shopping cart page
  public/css/cart/cart.css
  resources/views/cart/index.blade.php
Labels: enhancement

#95 #81 Delete unused view files
  public/images/delete-btn.svg
  public/images/minus.svg
  public/images/plus.svg
  resources/views/cart/cart.blade.php
  resources/views/dashboard.blade.php
  resources/views/welcome.blade.php
Labels: enhancement

#99 Fix CSS issues on the products page
  public/css/products.css
  resources/views/categories/show.blade.php
Labels: bug
