Repository kennyphan100/SOEN341, pull requests merged in 2022-03, with the labels that each got.

#112 #111 Create Categories table in database via migration
  app/Models/Category.php
  database/migrations/2022_03_06_170419_create_categories_table.php
Labels: task

#102 #65 Save the account type to database
  app/Http/Controllers/Auth/RegisteredUserController.php
  app/Models/User.php
  resources/views/auth/register.blade.php
  tests/Feature/Auth/RegistrationTest.php
Labels: task

#117 #116 Fix PHPUnit check fail
  app/Http/Controllers/Auth/RegisteredUserController.php
Labels: bug

#121 #86 Created two tables for checkout functionality
  app/Http/Controllers/OrderController.php
  app/Models/Order_Product.php
  resources/views/order/index.blade.php
Labels: task, priority

#122 #119 Clean up and fix bugs in profile page
  app/Http/Controllers/UserProfileController.php
  resources/views/userProfile/admin_category_add.blade.php
  resources/views/userProfile/admin_category_manage.blade.php
  resources/views/userProfile/admin_product_add.blade.php
  resources/views/userProfile/admin_product_manage.blade.php
  resources/views/userProfile/info.blade.php
  resources/views/userProfile/orders.blade.php
  resources/views/userProfile/payments.blade.php
  resources/views/userProfile/userProfileSidebar.blade.php
Labels: bug

#123 #89 Fixed 'brief description', added quantity of item in cart instead
  resources/views/order/index.blade.php
Labels: bug

#124 #91 Added required parameter to the email field in the checkout form
  resources/views/order/index.blade.php
Labels: bug

#125 #120 Add dropdown category list in admin's add product page
  app/Http/Controllers/AdminController.php
  resources/views/userProfile/admin_category_add.blade.php
  resources/views/userProfile/admin_product_add.blade.php
Labels: task

#127 #126 Implement admin functionality to add product
  app/Http/Controllers/AdminController.php
  public/images/levono_laptop.png
  public/images/the_alchemist.jpg
  resources/views/userProfile/admin_product_add.blade.php
  resources/views/userProfile/userProfileSidebar.blade.php
  routes/web.php
Labels: task

#128 #92 User's email is automatically added to checkout form
  resources/views/order/index.blade.php
Labels: enhancement

#136 #84 user now sees an order confirmation with their order number
  app/Http/Controllers/OrderController.php
  resources/views/order/orderMade.blade.php
Labels: priority

#139 Fix css bug on header
  public/css/products.css
  resources/views/categories/show.blade.php
Labels: bug

#143 Fix css in profile page and add missing image to a book
  public/css/products.css
  public/css/userProfile.css
  public/images/the_little_prince.jpg
  resources/views/userProfile/admin_category_add.blade.php
  resources/views/userProfile/admin_category_manage.blade.php
  resources/views/userProfile/admin_product_add.blade.php
  resources/views/userProfile/admin_product_show.blade.php
  resources/views/userProfile/info.blade.php
  resources/views/userProfile/userProfileSidebar.blade.php
Labels: task

#145 #144 Fix cancel order bug
  app/Http/Controllers/UserProfileController.php
Labels: bug
